
import blackmilktea from "./assets/drinkPics/Black Milk Tea.png";
import blackrosemilktea from "./assets/drinkPics/Black Rose Milk Tea.png";
import brownsugarlatte from "./assets/drinkPics/Brown Sugar Latte.png";
import dirtymatchalatte from "./assets/drinkPics/Dirty Matcha Latte.png";
import jasminemangopassionfruit from "./assets/drinkPics/Jasmine Mango Passionfruit.png";
import jasminemilktea from "./assets/drinkPics/Jasmine Milk Tea.png";
import kumquatlycheejasmine from "./assets/drinkPics/Kumquat Lychee Jasmine.png";
import matchalatte from "./assets/drinkPics/Matcha Latte.png";
import oolonghoneypeach from "./assets/drinkPics/Oolong Honey Peach.png";
import oolongmilktea from "./assets/drinkPics/Oolong Milk Tea.png";
import tarolatte from "./assets/drinkPics/Taro Latte.png";
import thaimilktea from "./assets/drinkPics/Thai Milk Tea.png";

const menuItems = [
  {
    id: 0,
    name: "Black milk Tea",
    category: "Classic Milk Tea",
    tea: ["Black"],
    milk: ["Regular Creamer (Dairy-free)", "Oat Milk", "Almond Milk", "Soy Milk"],
    flavor: [],
    toppings: ["Honey Boba", "Lychee Jelly", "Passionfruit Popping Boba"],
    ice: ['No Ice', 'Low Ice', 'Regular Ice'],
    sweetness:['0%','25%','50%', "75%",'100%'],
    price: 4.5,
    description: "Assam black tea with lactose-free creamer",
    picture: blackmilktea,
  },
  {
    id: 1,
    name: "Jasmine milk tea",
    category: "Classic Milk Tea",
    tea: ["Jasmine"],
    milk: ["Regular Creamer (Dairy-free)", "Oat Milk", "Almond Milk", "Soy Milk"],
    flavor: [],
    toppings: ["Honey Boba", "Lychee Jelly", "Passionfruit Popping Boba"],
    ice: ['No Ice', 'Low Ice', 'Regular Ice'],
    sweetness:['0%','25%','50%', "75%",'100%'],
    price: 4.5,
    description: "Jasmine green tea with lactose-free creamer",
    picture: jasminemilktea,
  },
  {
    id: 2,
    name: "Oolong milk tea",
    category: "Classic Milk Tea",
    tea: ["Oolong"],
    milk: ["Regular Creamer (Dairy-free)", "Oat Milk", "Almond Milk", "Soy Milk"],
    flavor: [],
    toppings: ["Honey Boba", "Lychee Jelly", "Passionfruit Popping Boba"],
    ice: ['No Ice', 'Low Ice', 'Regular Ice'],
    sweetness:['0%','25%','50%','100%'],
    price: 4.5,
    description: "Oolong tea with lactose-free creamer",
    picture: oolongmilktea,
  },
  {
    id: 3,
    name: "Thai milk tea",
    category: "Classic Milk Tea",
    tea: ["Thai"],
    milk: ["Regular Creamer (Dairy-free)", "Oat Milk", "Almond Milk", "Soy Milk"],
    flavor: [],
    toppings: ["Honey Boba", "Lychee Jelly", "Passionfruit Popping Boba"],
    ice: ['No Ice', 'Low Ice', 'Regular Ice'],
    sweetness:['0%','25%','50%','100%'],
    price: 4.5,
    description: "Thai tea with lactose-free creamer",
    picture: thaimilktea,
  },
  {
    id: 4,
    name: "Wintermelon Jasmine Milk Tea",
    category: "Classic Milk Tea",
    tea: ["Jasmine"],
    milk: ["Regular Creamer (Dairy-free)", "Oat Milk", "Almond Milk", "Soy Milk"],
    flavor: ["Wintermelon"],
    toppings: ["Honey Boba", "Lychee Jelly", "Passionfruit Popping Boba"],
    ice: ['No Ice', 'Low Ice', 'Regular Ice'],
    sweetness:['25%','50%', "75%",'100%'],
    price: 4.5,
    description: "Thai tea with lactose-free creamer",
    picture: jasminemilktea,
  },
  {
    id: 5,
    name: "Rose Black Milk Tea",
    category: "Classic Milk Tea",
    tea: ["Black"],
    milk: ["Regular Creamer (Dairy-free)", "Oat Milk", "Almond Milk", "Soy Milk"],
    flavor: ["Rose"],
    toppings: ["Honey Boba", "Lychee Jelly", "Passionfruit Popping Boba"],
    ice: ['No Ice', 'Low Ice', 'Regular Ice'],
    sweetness:['25%','50%', "75%",'100%'],
    price: 4.5,
    description: "Rose syrup and assam black tea with lactose-free creamer",
    picture: blackrosemilktea,
  },
  {
    id: 6,
    name: "Matcha Latte",
    category: "Fresh Milk Lattes",
    tea: ["Matcha"],
    milk: ["Fresh Milk", "Oat Milk", "Almond Milk", "Soy Milk"],
    flavor: [],
    toppings: ["Honey Boba", "Lychee Jelly", "Passionfruit Popping Boba"],
    ice: [],
    sweetness:[],
    price: 5.0,
    description: "Matcha with fresh milk",
    picture: matchalatte,
  },
  {
    id: 7,
    name: "Dirty Matcha Latte",
    category: "Fresh Milk Lattes",
    tea: ["Dirty Matcha"],
    milk: ["Fresh Milk", "Oat Milk", "Almond Milk", "Soy Milk"],
    flavor: [],
    toppings: ["Honey Boba", "Lychee Jelly", "Passionfruit Popping Boba"],
    ice: [],
    sweetness:[],
    price: 5.0,
    description: "Matcha and brown sugar with fresh milk",
    picture: dirtymatchalatte,
  },
  {
    id: 8,
    name: "Taro Latte",
    category: "Fresh Milk Lattes",
    tea: ["Taro"],
    milk: ["Fresh Milk", "Oat Milk", "Almond Milk", "Soy Milk"],
    flavor: [],
    toppings: ["Honey Boba", "Lychee Jelly", "Passionfruit Popping Boba"],
    ice: ['No Ice', 'Low Ice', 'Regular Ice'],
    sweetness:['0%','25%','50%', "75%",'100%'],
    price: 5.0,
    description: "Taro with fresh milk",
    picture: tarolatte,
  },
  {
    id: 9,
    name: "Brown Sugar Latte",
    category: "Fresh Milk Lattes",
    tea: ["Brown Sugar"],
    milk: ["Fresh Milk", "Oat Milk", "Almond Milk", "Soy Milk"],
    flavor: [],
    toppings: ["Honey Boba", "Lychee Jelly", "Passionfruit Popping Boba"],
    ice: [],
    sweetness: [],
    price: 5.0,
    description: "Brown sugar with fresh milk",
    picture: brownsugarlatte,
  },
  {
    id: 10,
    name: "Mango Passion Fruit Jasmine Tea",
    category: "Fruit Teas",
    tea: ["Jasmine"],
    milk: [],
    flavor: ["Mango, Passionfruit"],
    toppings: ["Honey Boba", "Lychee Jelly", "Passionfruit Popping Boba"],
    ice: ['No Ice', 'Low Ice', 'Regular Ice'],
    sweetness:['25%','50%', "75%",'100%'],
    price: 4.5,
    description: "Mango and passionfruit syrup with jasmine green tea",
    picture: jasminemangopassionfruit,
  },
  {
    id: 11,
    name: "Kumquat Lychee Green Tea",
    category: "Fruit Teas",
    tea: ["Jasmine"],
    milk: [],
    flavor: ["Kumquat, Lychee"],
    toppings: ["Honey Boba", "Lychee Jelly", "Passionfruit Popping Boba"],
    ice: ['No Ice', 'Low Ice', 'Regular Ice'],
    sweetness:['25%','50%', "75%",'100%'],
    price: 4.5,
    description: "Kumquat and lychee syrup with jasmine green tea",
    picture: kumquatlycheejasmine,
  },
  {
    id: 12,
    name: "Honey Peach Oolong Tea",
    category: "Fruit Teas",
    tea: ["Oolong"],
    milk: [],
    flavor: ["Honey, Peach"],
    toppings: ["Honey Boba", "Lychee Jelly", "Passionfruit Popping Boba"],
    ice: ['No Ice', 'Low Ice', 'Regular Ice'],
    sweetness:['25%','50%', "75%",'100%'],
    price: 4.5,
    description: "Honey and peach syrup with oolong tea",
    picture: oolonghoneypeach,
  },
  {
    id: 13,
    name: "Custom Fruit Tea",
    category: "Fruit Teas",
    tea: ["Black", "Jasmine", "Oolong"],
    milk: [],
    flavor: ["Mango", "Peach", "Passion Fruit", "Lychee", "Kumquat", "Rose"],
    toppings: ["Honey Boba", "Lychee Jelly", "Passionfruit Popping Boba"],
    ice: ['No Ice', 'Low Ice', 'Regular Ice'],
    sweetness:['25%','50%', "75%",'100%'],
    price: 5.0,
    description: "Make your own drink!",
  },
  {
    id: 14,
    name: "Today's Special",
    category: "Specials",
    tea: ["Black", "Jasmine", "Oolong"],
    milk: [],
    flavor: ["Mango", "Peach", "Passion Fruit", "Lychee", "Kumquat", "Rose"],
    toppings: ["Honey Boba", "Lychee Jelly", "Passionfruit Popping Boba"],
    ice: ['No Ice', 'Low Ice', 'Regular Ice'],
    sweetness:['25%','50%', "75%",'100%'],
    price: 5.0,
    description: "Today's special offering. Check our instagram @milkandhoneyclaremont for details!",
  },
];